### ISSUE TITLE
Are you using spdlog in example C ?

### ISSUE THREAD

**Issue by bsergean** [Timmmm/SpdlogBench#1]
I don't see any reference to spdlog in example C ... so it's unclear to me if it's only fmt library which is used in that case.

I have a linux machine running in virtualbox and with this config it's quite slow to compile.

**Comment by Timmmm** [comment]
Yes, C uses spdlog. The code in the readme is only showing the header (since that is the part that takes up all the compilation time). Example C only uses spdlog in the .cpp file, which is still slow but unlike the header it only gets compiled once.

The idea was that the only bit of spdlog that really needs to be header-only is fmt, because it uses templates. So I just put the fmt part in the header, and then [the implementation of `void logit(std::string&& s)`](https://github.com/Timmmm/SpdlogBench/blob/master/LogInterface.cpp#L32-L37) calls the spdlog functions.

**Comment by Timmmm** [comment]
Also note that spdlog now does support [a static library mode](https://github.com/gabime/spdlog#static-lib-version-recommended---much-faster-compile-times), which I haven't actually used yet but I assume works the same as example C.

**Comment by bsergean** [comment]
Thanks for the explanation ; using std::string as a signature isn't great though, usually what I want is python style formatting.

I actually tried the static lib mode, and the compile speed is still not great which is why I'm still looking for a good solution.

**Comment by Timmmm** [comment]
You still get python style formatting via the template version which is also in the header.

**Comment by Timmmm** [comment]
To be explicit:

## `log.h`

```
#pragma once

#include <fmt/format.h>

void trace(std::string&& s);
void info(std::string&& s);
// ...

template <typename... Args>
void trace(const char* s, const Args&... args)
{
	trace(fmt::format(s, args...));
}

template <typename... Args>
void info(const char* s, const Args&... args)
{
	info(fmt::format(s, args...));
}
// ...
```

## `log.cpp`

	#define SPDLOG_FMT_EXTERNAL 1
	#include <spdlog/spdlog.h>

	void trace(std::string&& s)
	{
		auto log = spdlog::get("default");
		if (log)
			log->trace(s);
	}
	void info(std::string&& s)
	{
		auto log = spdlog::get("default");
		if (log)
			log->info(s);
	}
	// ...

## `whatever.cpp`

```
#include "log.h"

int foo(int i) {
   trace("i = {}", i);
}
```
